version: 2.1

jobs:
  build:
    docker:
      - image: circleci/php:7.4
    steps:
      - checkout

      - run:
          name: Install dependencies
          command: |
            cd ./src
            sudo docker-php-ext-install pdo pdo_mysql
            composer install

      - run:
          name: Set up environment
          command: |
            cd ./src
            cp .env.testing .env
            php artisan config:cache

      - run:
          name: Run tests
          command: |
            cd ./src
            php artisan migrate --env=testing
            php ./vendor/bin/phpunit --configuration=phpunit.xml
