version: 2.1

jobs:
  build:
    docker:
      - image: circleci/php:7.4
      - image: circleci/mysql:8.0
        environment:
          DB_HOST: mysql
          DB_CONNECTION: mysql
          MYSQL_ROOT_PASSWORD: root
          LARAVEL_BYPASS_ENV_CHECK: 1
    steps:
      - checkout

      - run:
          name: Install MySQL client
          command: |
            sudo apt-get update
            sudo apt-get install -y default-mysql-client

      - run:
          name: Install dependencies
          command: |
            cd ./src
            sudo docker-php-ext-install pdo pdo_mysql
            composer install

      - run:
          name: Set up environment
          command: |
            cd ./src
            cp .env.example .env.testing

      - run:
          name: Create test database
          command: |
            mysql -u root -proot -h 127.0.0.1 -e "CREATE DATABASE IF NOT EXISTS demo_test;"

      - run:
          name: Clear cache
          command: |
            cd ./src
            php artisan cache:clear
            php artisan config:clear

      - run:
          name: Run tests
          command: |
            cd ./src
            php artisan migrate:fresh --env=testing
            php ./vendor/bin/phpunit --testsuite=Feature
