version: 2.1

jobs:
  build:
    docker:
      - image: circleci/php:7.4
        environment:
            PHP_MEMORY_LIMIT: "512M"
      - image: circleci/mysql:8.0  # MySQLサービスを追加
    steps:
      - checkout

      - run:
          name: Install dependencies
          command: |
            cd ./src
            sudo docker-php-ext-install pdo pdo_mysql
            composer install

      - run:
          name: Set up environment
          command: |
            cd ./src
            cp .env.testing .env
            sed -i 's/DB_HOST=.*/DB_HOST=mysql/' .env  # DB_HOSTをmysqlに設定
            sed -i 's/DB_USERNAME=.*/DB_USERNAME=root/' .env  # DB_USERNAMEをrootに設定
            sed -i 's/DB_PASSWORD=.*/DB_PASSWORD=root/' .env  # DB_PASSWORDを設定
      - run:
          name: Clear cache
          command: |
            cd ./src
            php artisan cache:clear
            php artisan config:clear
            php artisan route:clear
            php artisan view:clear

      - run:
          name: Run tests
          command: |
            cd ./src
            php artisan migrate --env=testing
            php ./vendor/bin/phpunit --configuration=phpunit.xml
