version: 2.1

jobs:
  build:
    docker:
      - image: circleci/php:7.4
        environment:
            PHP_MEMORY_LIMIT: "512M"
    steps:
      - checkout

      - run:
          name: Install Docker Compose
          command: |
            sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
            sudo chmod +x /usr/local/bin/docker-compose

      - run:
          name: Start services
          command: |
            cd ./src
            docker-compose up -d

      - run:
          name: Install dependencies
          command: |
            cd ./src
            sudo docker-php-ext-install pdo pdo_mysql
            composer install

      - run:
          name: Set up environment
          command: |
            cd ./src
            cp .env.testing .env
      - run:
          name: Clear cache
          command: |
            cd ./src
            php artisan cache:clear
            php artisan config:clear
            php artisan route:clear
            php artisan view:clear

      - run:
          name: Run tests
          command: |
            cd ./src
            php artisan migrate --env=testing
            php ./vendor/bin/phpunit --configuration=phpunit.xml
