version: 2.1

jobs:
  build:
    docker:
      - image: circleci/php:7.4
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            cd ./src
            cp .env.testing .env
            composer install
      - run:
          name: Run tests
          command: cd ./src && ./vendor/bin/phpunit
