version: 2.1

jobs:
  build:
    docker:
      - image: circleci/php:7.4
        environment:
            PHP_MEMORY_LIMIT: "512M"
      - image: circleci/mysql:5.7
    environment:
      - DB_CONNECTION: circle_testing

    environment:
      APP_ENV: testing
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: demo_test
      DB_USERNAME: root
      DB_PASSWORD: root
    steps:
      - checkout

      - run:
          name: Install dependencies
          command: |
            cd ./src
            sudo docker-php-ext-install pdo pdo_mysql
            composer install
      
      - run:
          name: Wait for MySQL to be ready
          command: |
            for i in $(seq 1 60); do  # 待機時間を60秒に変更
              if mysqladmin ping -h mysql --silent; then
                break
              fi
              echo "Waiting for MySQL..."
              sleep 1
            done

      - run:
          name: Set up environment
          command: |
            cd ./src
            cp .env.testing .env
      - run:
          name: Clear cache
          command: |
            cd ./src
            php artisan cache:clear
            php artisan config:clear

      - run:
          name: Run tests
          command: |
            cd ./src
            php artisan migrate --env=testing
            php ./vendor/bin/phpunit
