version: 2.1
jobs:
  build:
    docker:
      - image: circleci/php:7.4-node-browsers
    working_directory: src
    steps:
      - checkout
      - run:
          name: Clear cache
          command: |
            echo "Clearing cache..."
            rm -rf ~/.cache/composer/*
            rm -rf ~/.npm/*
      - run: sudo composer self-update --2
      - run: composer install -n --prefer-dist
      - run: npm ci
      - run: npm run dev
      - run:
          name: php test
          command: vendor/bin/phpunit
